# Generated by Django 5.2.5 on 2025-09-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profilepictures/profilepic.jpg', upload_to='profilepictures'),
        ),
    ]
